/**
 * Generated by endpoints-angular-client-generator (version 0.0.1-2)
 * Arguments:
 *   endpoints-angular-client-generator -d ../../target/jasify-v1-rest.discovery.json -s -o src/main/client/jasify/providers
 */
/*global angular*/
(function (angular) {
    'use strict';
    angular.module('jasify.endpoint', ['ng']);
}(angular));
